MAX_TEXT_LENGTH: 128
VOCAB: ./datasets/captions_vocab_bird.pickle
LANGUAGE_ENCODER: ./datasets/text_encoder_bird.pth
IMAGE_ENCODER: ./datasets/image_encoder_bird.pth

CAPTION: ./datasets/CUB_200_2011/caption.json